[package]
name = "tuplan-llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = { path = "../llvm-sys", version = "150.0.0" }
libc = "0.2.126"