[package]
name = "tuplan-llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = { git = "https://github.com/Bitbot25/llvm-sys", version = "140.0.0" }
libc = "0.2.126"
